# Generated by Django 4.2.1 on 2023-05-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0003_customer_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(default="customer", max_length=255),
        ),
    ]
