# Generated by Django 4.2.1 on 2023-05-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0004_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_type",
            new_name="user_level",
        ),
    ]
