# Generated by Django 4.2.1 on 2023-05-26 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0005_rename_user_type_user_user_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="auth_app.owner",
            ),
            preserve_default=False,
        ),
    ]
