# Generated by Django 4.2.1 on 2023-05-26 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0006_employee_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="auth_app.owner",
            ),
        ),
    ]
