# Generated by Django 4.2.1 on 2023-05-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0007_alter_employee_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="spent",
            field=models.IntegerField(default=0),
        ),
    ]
