# Generated by Django 4.2.1 on 2023-05-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0008_customer_balance_customer_spent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="Owner",
        ),
    ]
