# Generated by Django 4.2.1 on 2023-05-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_promotion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotion",
            old_name="promotion_name",
            new_name="name",
        ),
    ]
